name: E2E
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Run e2e tests
        uses: cypress-io/github-action@v1
        with:
          build: npm run build --prod
          start: npm start
          working-directory: apps/frontend-e2e
          config-file: apps/frontend-e2e/cypress.json



